services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    env_file:
      - .env
    command: ['node', 'packages/backend', '--config', 'app-config.yaml']
    networks:
      - backstage
    ports:
      - 7007:7007
  db:
    image: postgres:17.6-alpine3.21
    env_file:
      - .env
    networks:
      - backstage
    ports:
      - 5432:5432

networks:
  backstage:
